// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Morty.Data;

#nullable disable

namespace Morty.Data.Migrations
{
    [DbContext(typeof(MortyDbContext))]
    partial class MortyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Morty.Entities.EnvConfigGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EnvConfigGroups");
                });

            modelBuilder.Entity("Morty.Entities.EnvConfigRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EnvConfigGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromPhase")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToPhase")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvConfigGroupId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EnvConfigRules");
                });

            modelBuilder.Entity("Morty.Entities.EnvVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultValue")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("EnvConfigGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnvConfigGroupId");

                    b.ToTable("EnvVariables");
                });

            modelBuilder.Entity("Morty.Entities.ExecutionOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CostUsd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IterationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParsedOutput")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IterationId");

                    b.ToTable("ExecutionOutputs");
                });

            modelBuilder.Entity("Morty.Entities.Iteration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CostUsd")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IterationNum")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("Iterations");
                });

            modelBuilder.Entity("Morty.Entities.PhaseHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("PhaseHistories");
                });

            modelBuilder.Entity("Morty.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoryId", "Type", "Version")
                        .IsUnique();

                    b.ToTable("Plans");
                });

            modelBuilder.Entity("Morty.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefaultEnvConfigGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrdJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingDirectory")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DefaultEnvConfigGroupId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Morty.Entities.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentIteration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RunningStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoryId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserAcceptanceCriteria")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Stories");
                });

            modelBuilder.Entity("Morty.Entities.StoryDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DependsOnStoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnStoryId");

                    b.HasIndex("StoryId");

                    b.ToTable("StoryDependencies");
                });

            modelBuilder.Entity("Morty.Entities.StoryEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("StoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("StoryEvents");
                });

            modelBuilder.Entity("Morty.Entities.Verification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IterationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IterationId");

                    b.ToTable("Verifications");
                });

            modelBuilder.Entity("Morty.Entities.EnvConfigRule", b =>
                {
                    b.HasOne("Morty.Entities.EnvConfigGroup", "EnvConfigGroup")
                        .WithMany()
                        .HasForeignKey("EnvConfigGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Morty.Entities.Project", "Project")
                        .WithMany("EnvConfigRules")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnvConfigGroup");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Morty.Entities.EnvVariable", b =>
                {
                    b.HasOne("Morty.Entities.EnvConfigGroup", "EnvConfigGroup")
                        .WithMany("Variables")
                        .HasForeignKey("EnvConfigGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnvConfigGroup");
                });

            modelBuilder.Entity("Morty.Entities.ExecutionOutput", b =>
                {
                    b.HasOne("Morty.Entities.Iteration", "Iteration")
                        .WithMany("ExecutionOutputs")
                        .HasForeignKey("IterationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iteration");
                });

            modelBuilder.Entity("Morty.Entities.Iteration", b =>
                {
                    b.HasOne("Morty.Entities.Story", "Story")
                        .WithMany("Iterations")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Morty.Entities.PhaseHistory", b =>
                {
                    b.HasOne("Morty.Entities.Story", "Story")
                        .WithMany("PhaseHistories")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Morty.Entities.Plan", b =>
                {
                    b.HasOne("Morty.Entities.Story", "Story")
                        .WithMany("Plans")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Morty.Entities.Project", b =>
                {
                    b.HasOne("Morty.Entities.EnvConfigGroup", "DefaultEnvConfigGroup")
                        .WithMany()
                        .HasForeignKey("DefaultEnvConfigGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultEnvConfigGroup");
                });

            modelBuilder.Entity("Morty.Entities.Story", b =>
                {
                    b.HasOne("Morty.Entities.Project", "Project")
                        .WithMany("Stories")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Morty.Entities.StoryDependency", b =>
                {
                    b.HasOne("Morty.Entities.Story", "DependsOnStory")
                        .WithMany("Dependents")
                        .HasForeignKey("DependsOnStoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Morty.Entities.Story", "Story")
                        .WithMany("Dependencies")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DependsOnStory");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Morty.Entities.StoryEvent", b =>
                {
                    b.HasOne("Morty.Entities.Story", "Story")
                        .WithMany("Events")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Morty.Entities.Verification", b =>
                {
                    b.HasOne("Morty.Entities.Iteration", "Iteration")
                        .WithMany("Verifications")
                        .HasForeignKey("IterationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Iteration");
                });

            modelBuilder.Entity("Morty.Entities.EnvConfigGroup", b =>
                {
                    b.Navigation("Variables");
                });

            modelBuilder.Entity("Morty.Entities.Iteration", b =>
                {
                    b.Navigation("ExecutionOutputs");

                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("Morty.Entities.Project", b =>
                {
                    b.Navigation("EnvConfigRules");

                    b.Navigation("Stories");
                });

            modelBuilder.Entity("Morty.Entities.Story", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Dependents");

                    b.Navigation("Events");

                    b.Navigation("Iterations");

                    b.Navigation("PhaseHistories");

                    b.Navigation("Plans");
                });
#pragma warning restore 612, 618
        }
    }
}
